// <auto-generated />
using System;
using ERP_System.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ERP_System.DAL.Migrations
{
    [DbContext(typeof(ERP_SystemDbContext))]
    [Migration("20230620231422_addPaidTpPurchaseThrowback")]
    partial class addPaidTpPurchaseThrowback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ERP_System.Tables.ActionsPage", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionName")
                        .HasColumnType("int");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PageId");

                    b.ToTable("ActionsPages", "Page");
                });

            modelBuilder.Entity("ERP_System.Tables.Attachment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("Attachments", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProcessAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProcessType")
                        .HasColumnType("int");

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Clients", "People");
                });

            modelBuilder.Entity("ERP_System.Tables.Invoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Invoices", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.InvoiceDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QtyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceDetails", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.ItemGrpoup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("ItemGrpoups", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.Page", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Pages", "Page");
                });

            modelBuilder.Entity("ERP_System.Tables.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BarCodePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BarCodeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUnitOfQty")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameUnitOfQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("QtyInStock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("GroupId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Products", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.ProductUnit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PurchasingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitBarcodePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitBarcodeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProductUnits", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseInvoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("InvoiceTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("PurchaseInvoices", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseInvoiceDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductBarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PurchaseInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PurchasingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalQtyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchaseInvoiceDetails", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseThrowback", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("InvoiceTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("PurchaseThrowbacks", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseThrowbackDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductBarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PurchaseThrowbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PurchasingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalQtyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PurchaseThrowbackId");

                    b.ToTable("PurchaseThrowbackDetails", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleInvoice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("InvoiceTotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InvoiceTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("SaleInvoices", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleInvoiceDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountPProduct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ItemUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductBarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SaleInvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalQtyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SaleInvoiceId");

                    b.ToTable("SaleInvoiceDetails", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleThrowback", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("InvoiceTotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StockName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("SaleThrowbacks", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleThrowbackDetail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ItemUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductBarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SaleThrowbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalQtyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("SaleThrowbackId");

                    b.ToTable("SaleThrowbackDetails", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.Setting", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Settings", "Setting");
                });

            modelBuilder.Entity("ERP_System.Tables.Stock", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Stocks", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.StockProduct", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockId");

                    b.ToTable("StockProducts", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.Supplier", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProcessAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProcessType")
                        .HasColumnType("int");

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Suppliers", "People");
                });

            modelBuilder.Entity("ERP_System.Tables.Unit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Units", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeOfReset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScreenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UseDefaultPassword")
                        .HasColumnType("bit");

                    b.Property<int?>("UserClassification")
                        .HasColumnType("int");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users", "People");
                });

            modelBuilder.Entity("ERP_System.Tables.UserPermission", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PageActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("PageActionId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("UserPermissions", "People");
                });

            modelBuilder.Entity("ERP_System.Tables.UserStock", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStocks", "People");
                });

            modelBuilder.Entity("ERP_System.Tables.UserType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AddedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("UserTypes", "Guide");
                });

            modelBuilder.Entity("ERP_System.Tables.ActionsPage", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("ActionsPageCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("ActionsPageDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("ActionsPageModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.Page", "Page")
                        .WithMany("ActionsPages")
                        .HasForeignKey("PageId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("ERP_System.Tables.Attachment", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("AttatchCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("AttatchDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("AttatchModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.Product", "Product")
                        .WithMany("Attachments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP_System.Tables.Client", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("ClientCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("ClientDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("ClientModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.Invoice", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.InvoiceDetail", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Invoice");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERP_System.Tables.ItemGrpoup", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("ItemGroupCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("ItemGroupDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("ItemGroupModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.Page", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("PageCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("PageDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("PageModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.Product", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("ProductCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("ProductDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.ItemGrpoup", "Group")
                        .WithMany("Products")
                        .HasForeignKey("GroupId");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("ProductModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("Group");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.ProductUnit", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("ProductUnitCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("ProductUnitDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("ProductUnitModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.Product", "Product")
                        .WithMany("ProductUnits")
                        .HasForeignKey("ProductId");

                    b.HasOne("ERP_System.Tables.Unit", "Unit")
                        .WithMany("ProductUnits")
                        .HasForeignKey("UnitId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseInvoice", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("PurchaseInvoiceCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("PurchaseInvoiceDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("PurchaseInvoiceModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseInvoiceDetail", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("PurchaseInvoiceDetailCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("PurchaseInvoiceDetailDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("PurchaseInvoiceDetailModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseInvoiceDetail")
                        .HasForeignKey("PurchaseInvoiceId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseThrowback", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("PurchaseThrowbackCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("PurchaseThrowbackDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("PurchaseThrowbackModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseThrowbackDetail", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("PurchaseThrowbackDetailCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("PurchaseThrowbackDetailDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("PurchaseThrowbackDetailModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.PurchaseThrowback", "PurchaseThrowback")
                        .WithMany("PurchaseThrowbackDetails")
                        .HasForeignKey("PurchaseThrowbackId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("PurchaseThrowback");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleInvoice", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("SaleInvoiceCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("SaleInvoiceDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("SaleInvoiceModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleInvoiceDetail", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("SaleInvoiceDetailCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("SaleInvoiceDetailDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("SaleInvoiceDetailModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.SaleInvoice", "SaleInvoice")
                        .WithMany("SaleInvoiceDetail")
                        .HasForeignKey("SaleInvoiceId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("SaleInvoice");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleThrowback", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("SaleThrowbackCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("SaleThrowbackDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("SaleThrowbackModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleThrowbackDetail", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("SaleThrowbackDetailCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("SaleThrowbackDetailDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("SaleThrowbackDetailModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.SaleThrowback", "SaleThrowback")
                        .WithMany("SaleInvoiceDetails")
                        .HasForeignKey("SaleThrowbackId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("SaleThrowback");
                });

            modelBuilder.Entity("ERP_System.Tables.Setting", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("SettingCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("SettingDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("SettingModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.Stock", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("StockCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("StockDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("StockModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.StockProduct", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("StockProductCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("StockProductDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("StockProductModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.Product", "Product")
                        .WithMany("StockProducts")
                        .HasForeignKey("ProductId");

                    b.HasOne("ERP_System.Tables.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Product");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("ERP_System.Tables.Supplier", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("SupplierCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("SupplierDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("SupplierModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.Unit", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("UnitCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("UnitDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("UnitModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.User", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("UserCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("UserDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("UserModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("ERP_System.Tables.UserPermission", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("UserPermissionCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("UserPermissionDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("UserPermissionModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.ActionsPage", "ActionsPage")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PageActionId");

                    b.HasOne("ERP_System.Tables.UserType", "UserType")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserTypeId");

                    b.Navigation("ActionsPage");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("ERP_System.Tables.UserStock", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("UserStockCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("UserStockDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("UserStockModified")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("ERP_System.Tables.Stock", "Stock")
                        .WithMany("UserStocks")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_System.Tables.User", "User")
                        .WithMany("UserStocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_System.Tables.UserType", b =>
                {
                    b.HasOne("ERP_System.Tables.User", "CreatedUser")
                        .WithMany("UserTypeCreated")
                        .HasForeignKey("AddedBy");

                    b.HasOne("ERP_System.Tables.User", "DeletedUser")
                        .WithMany("UserTypeDeleted")
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ERP_System.Tables.User", "ModifiedUser")
                        .WithMany("UserTypeModified")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedUser");

                    b.Navigation("DeletedUser");

                    b.Navigation("ModifiedUser");
                });

            modelBuilder.Entity("ERP_System.Tables.ActionsPage", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("ERP_System.Tables.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("ERP_System.Tables.ItemGrpoup", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ERP_System.Tables.Page", b =>
                {
                    b.Navigation("ActionsPages");
                });

            modelBuilder.Entity("ERP_System.Tables.Product", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("InvoiceDetails");

                    b.Navigation("ProductUnits");

                    b.Navigation("StockProducts");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseInvoiceDetail");
                });

            modelBuilder.Entity("ERP_System.Tables.PurchaseThrowback", b =>
                {
                    b.Navigation("PurchaseThrowbackDetails");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleInvoice", b =>
                {
                    b.Navigation("SaleInvoiceDetail");
                });

            modelBuilder.Entity("ERP_System.Tables.SaleThrowback", b =>
                {
                    b.Navigation("SaleInvoiceDetails");
                });

            modelBuilder.Entity("ERP_System.Tables.Stock", b =>
                {
                    b.Navigation("UserStocks");
                });

            modelBuilder.Entity("ERP_System.Tables.Unit", b =>
                {
                    b.Navigation("ProductUnits");
                });

            modelBuilder.Entity("ERP_System.Tables.User", b =>
                {
                    b.Navigation("ActionsPageCreated");

                    b.Navigation("ActionsPageDeleted");

                    b.Navigation("ActionsPageModified");

                    b.Navigation("AttatchCreated");

                    b.Navigation("AttatchDeleted");

                    b.Navigation("AttatchModified");

                    b.Navigation("ClientCreated");

                    b.Navigation("ClientDeleted");

                    b.Navigation("ClientModified");

                    b.Navigation("ItemGroupCreated");

                    b.Navigation("ItemGroupDeleted");

                    b.Navigation("ItemGroupModified");

                    b.Navigation("PageCreated");

                    b.Navigation("PageDeleted");

                    b.Navigation("PageModified");

                    b.Navigation("ProductCreated");

                    b.Navigation("ProductDeleted");

                    b.Navigation("ProductModified");

                    b.Navigation("ProductUnitCreated");

                    b.Navigation("ProductUnitDeleted");

                    b.Navigation("ProductUnitModified");

                    b.Navigation("PurchaseInvoiceCreated");

                    b.Navigation("PurchaseInvoiceDeleted");

                    b.Navigation("PurchaseInvoiceDetailCreated");

                    b.Navigation("PurchaseInvoiceDetailDeleted");

                    b.Navigation("PurchaseInvoiceDetailModified");

                    b.Navigation("PurchaseInvoiceModified");

                    b.Navigation("PurchaseThrowbackCreated");

                    b.Navigation("PurchaseThrowbackDeleted");

                    b.Navigation("PurchaseThrowbackDetailCreated");

                    b.Navigation("PurchaseThrowbackDetailDeleted");

                    b.Navigation("PurchaseThrowbackDetailModified");

                    b.Navigation("PurchaseThrowbackModified");

                    b.Navigation("SaleInvoiceCreated");

                    b.Navigation("SaleInvoiceDeleted");

                    b.Navigation("SaleInvoiceDetailCreated");

                    b.Navigation("SaleInvoiceDetailDeleted");

                    b.Navigation("SaleInvoiceDetailModified");

                    b.Navigation("SaleInvoiceModified");

                    b.Navigation("SaleThrowbackCreated");

                    b.Navigation("SaleThrowbackDeleted");

                    b.Navigation("SaleThrowbackDetailCreated");

                    b.Navigation("SaleThrowbackDetailDeleted");

                    b.Navigation("SaleThrowbackDetailModified");

                    b.Navigation("SaleThrowbackModified");

                    b.Navigation("SettingCreated");

                    b.Navigation("SettingDeleted");

                    b.Navigation("SettingModified");

                    b.Navigation("StockCreated");

                    b.Navigation("StockDeleted");

                    b.Navigation("StockModified");

                    b.Navigation("StockProductCreated");

                    b.Navigation("StockProductDeleted");

                    b.Navigation("StockProductModified");

                    b.Navigation("SupplierCreated");

                    b.Navigation("SupplierDeleted");

                    b.Navigation("SupplierModified");

                    b.Navigation("UnitCreated");

                    b.Navigation("UnitDeleted");

                    b.Navigation("UnitModified");

                    b.Navigation("UserCreated");

                    b.Navigation("UserDeleted");

                    b.Navigation("UserModified");

                    b.Navigation("UserPermissionCreated");

                    b.Navigation("UserPermissionDeleted");

                    b.Navigation("UserPermissionModified");

                    b.Navigation("UserStockCreated");

                    b.Navigation("UserStockDeleted");

                    b.Navigation("UserStockModified");

                    b.Navigation("UserStocks");

                    b.Navigation("UserTypeCreated");

                    b.Navigation("UserTypeDeleted");

                    b.Navigation("UserTypeModified");
                });

            modelBuilder.Entity("ERP_System.Tables.UserType", b =>
                {
                    b.Navigation("UserPermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
